### ISSUE TITLE
loading cluster config depends on external_api plugin to be activated

### ISSUE THREAD

**Issue by clenimar** [ufcg-lsd/asperathos-monitor#13]
if `external_api` plugin is not activated, the monitor will fail to load the cluster credentials.

to reproduce:
1. run monitor without external_api plugin.
2. it'll break:

```INFO:UtilsAPI:Traceback (most recent call last):
  File "/home/ubuntu/asperathos-monitor/monitor/utils/api.py", line 76, in handler
    return func(**kwargs)
  File "/home/ubuntu/asperathos-monitor/monitor/api/v10.py", line 32, in start_monitoring
    return u.render(api.start_monitoring(data, app_id))
  File "/home/ubuntu/asperathos-monitor/monitor/service/api/v10.py", line 47, in start_monitoring
    executor = builder.get_monitor(plugin, app_id, plugin_info)
  File "/home/ubuntu/asperathos-monitor/monitor/plugins/builder.py", line 47, in get_monitor
    executor = KubeJobProgress(app_id, plugin_info, retries=api.retries)
  File "/home/ubuntu/asperathos-monitor/monitor/plugins/kubejobs/plugin.py", line 50, in __init__
    kubernetes.config.load_kube_config(api.k8s_manifest)
AttributeError: 'module' object has no attribute 'k8s_manifest'
```

**Comment by rafaelvfalc** [comment]
This issue happened because the `kubejobs` plugin requires the `k8s-manifest` variable to be previously computed to work correctly, and in the previously version of this code this variable is only computed when the `external-api` is actived.
